use std::fmt::Write as _;
use std::fs;

use anyhow::{Result, bail, ensure};

use crate::domain::{ImageCatalog, ImageTarget, SourceArchive};

const GENERATED_HEADER: &str = "# ------------------------------------------------------------------------------\n# NOTE: THIS FILE IS GENERATED BY `keeline render`.\n# SOURCE OF TRUTH: image.toml\n# ------------------------------------------------------------------------------\n\n";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyncStatus {
    Generated,
    Updated,
    Unchanged,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct SyncSummary {
    pub generated: usize,
    pub updated: usize,
    pub unchanged: usize,
}

pub fn render(target: &ImageTarget) -> Result<String> {
    match target.family.as_str() {
        "debian" => render_debian(target),
        "jdk" => render_jdk(target),
        family => bail!("rendering is not implemented for family `{family}`"),
    }
}

pub fn sync_target(target: &ImageTarget) -> Result<SyncStatus> {
    let rendered = render(target)?;
    let existed = target.dockerfile.exists();
    let existing = if existed {
        fs::read_to_string(&target.dockerfile)?
    } else {
        String::new()
    };

    if existing == rendered {
        return Ok(SyncStatus::Unchanged);
    }

    fs::write(&target.dockerfile, rendered)?;

    if existed {
        Ok(SyncStatus::Updated)
    } else {
        Ok(SyncStatus::Generated)
    }
}

pub fn sync_catalog(catalog: &ImageCatalog) -> Result<SyncSummary> {
    let mut summary = SyncSummary::default();

    for target in &catalog.targets {
        match sync_target(target)? {
            SyncStatus::Generated => summary.generated += 1,
            SyncStatus::Updated => summary.updated += 1,
            SyncStatus::Unchanged => summary.unchanged += 1,
        }
    }

    Ok(summary)
}

pub fn check_target(target: &ImageTarget) -> Result<()> {
    ensure!(
        target.dockerfile.exists(),
        "dockerfile is missing for `{}`: {}",
        target.id,
        target.dockerfile.display()
    );

    let rendered = render(target)?;
    let existing = fs::read_to_string(&target.dockerfile)?;

    ensure!(
        existing == rendered,
        "dockerfile is out of sync for `{}`: run `cargo run -- render {}`",
        target.id,
        target.id
    );

    Ok(())
}

pub fn check_catalog(catalog: &ImageCatalog) -> Result<()> {
    for target in &catalog.targets {
        check_target(target)?;
    }

    Ok(())
}

fn render_debian(target: &ImageTarget) -> Result<String> {
    let mut output = String::new();
    let command = serde_json::to_string(&target.command)?;

    output.push_str(GENERATED_HEADER);
    writeln!(output, "FROM {}", target.base_image)?;
    output.push('\n');
    append_label_args(&mut output)?;
    append_common_labels(&mut output, target)?;
    output.push('\n');
    writeln!(output, "CMD {command}")?;

    Ok(output)
}

fn render_jdk(target: &ImageTarget) -> Result<String> {
    let source = target
        .source
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("jdk image `{}` is missing source metadata", target.id))?;
    let java = target
        .java
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("jdk image `{}` is missing java metadata", target.id))?;
    let builder_image = builder_image(&target.base_image);
    let command = serde_json::to_string(&target.command)?;
    let trim_paths: Vec<String> = java
        .trim_files
        .iter()
        .map(|path| normalize_trim_path(path))
        .collect();
    let case_statement = render_archive_case_statement(&source.archives)?;

    let mut output = String::new();
    output.push_str(GENERATED_HEADER);
    writeln!(output, "FROM {builder_image} AS source")?;
    writeln!(output)?;
    writeln!(output, "ENV JAVA_HOME={}", java.java_home)?;
    writeln!(output, "ENV JAVA_RELEASE={}", source.release)?;
    writeln!(output)?;
    append_apt_install(&mut output, &java.builder_packages, false)?;
    writeln!(output)?;
    output.push_str("RUN set -eux; \\\n");
    output.push_str("    ARCH=\"$(dpkg --print-architecture)\"; \\\n");
    output.push_str("    case \"${ARCH}\" in \\\n");
    output.push_str(&case_statement);
    output.push_str("    esac; \\\n");
    output.push_str("    wget --progress=dot:giga -O /tmp/openjdk.tar.gz \"${BINARY_URL}\"; \\\n");
    output.push_str(
        "    wget --progress=dot:giga -O /tmp/openjdk.tar.gz.sig \"${BINARY_URL}.sig\"; \\\n",
    );
    output.push_str("    export GNUPGHOME=\"$(mktemp -d)\"; \\\n");
    writeln!(
        output,
        "    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys {}; \\",
        shell_quote(&source.gpg_key)
    )?;
    output.push_str("    gpg --batch --verify /tmp/openjdk.tar.gz.sig /tmp/openjdk.tar.gz; \\\n");
    output.push_str("    rm -rf \"${GNUPGHOME}\" /tmp/openjdk.tar.gz.sig; \\\n");
    output.push_str("    echo \"${ESUM} */tmp/openjdk.tar.gz\" | sha256sum -c -; \\\n");
    output.push_str("    mkdir -p \"$JAVA_HOME\"; \\\n");
    writeln!(
        output,
        "    tar --extract --file /tmp/openjdk.tar.gz --directory \"$JAVA_HOME\" --strip-components {} --no-same-owner; \\",
        source.strip_components
    )?;
    output.push_str("    rm -f /tmp/openjdk.tar.gz");
    for path in &trim_paths {
        write!(output, " {path}")?;
    }
    output.push_str(";\n\n");

    writeln!(output, "FROM {}", target.base_image)?;
    writeln!(output)?;
    writeln!(output, "ENV JAVA_HOME={}", java.java_home)?;
    output.push_str("ENV PATH=\"${JAVA_HOME}/bin:${PATH}\"\n");
    output.push_str("ENV LANG=\"en_US.UTF-8\"\n");
    output.push_str("ENV LANGUAGE=\"en_US:en\"\n");
    output.push_str("ENV LC_ALL=\"en_US.UTF-8\"\n");
    output.push('\n');
    append_label_args(&mut output)?;
    append_apt_install(&mut output, &java.runtime_packages, true)?;
    writeln!(output)?;
    writeln!(
        output,
        "COPY --from=source {} {}",
        java.java_home, java.java_home
    )?;
    writeln!(output)?;
    output.push_str("RUN set -eux; \\\n");
    output.push_str(
        "    find \"$JAVA_HOME/lib\" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf; \\\n",
    );
    output.push_str("    ldconfig");
    if !java.verify_commands.is_empty() {
        output.push_str("; \\\n");
        for (index, command) in java.verify_commands.iter().enumerate() {
            output.push_str("    ");
            output.push_str(command);
            if index + 1 == java.verify_commands.len() {
                output.push('\n');
            } else {
                output.push_str("; \\\n");
            }
        }
    } else {
        output.push('\n');
    }
    writeln!(output)?;
    append_common_labels(&mut output, target)?;
    output.push('\n');
    writeln!(output, "CMD {command}")?;

    Ok(output)
}

fn append_label_args(output: &mut String) -> Result<()> {
    output.push_str("ARG KEELINE_IMAGE_SOURCE=https://github.com/unknown/unknown\n");
    output.push_str("ARG KEELINE_IMAGE_REVISION=unknown\n");
    output.push_str("ARG KEELINE_IMAGE_LICENSES=Apache-2.0\n");
    Ok(())
}

fn append_common_labels(output: &mut String, target: &ImageTarget) -> Result<()> {
    writeln!(
        output,
        "LABEL org.opencontainers.image.title=\"{}\" \\",
        docker_escape(&target.title)
    )?;
    writeln!(
        output,
        "      org.opencontainers.image.description=\"{}\" \\",
        docker_escape(&target.description)
    )?;
    output.push_str("      org.opencontainers.image.source=\"${KEELINE_IMAGE_SOURCE}\" \\\n");
    output.push_str("      org.opencontainers.image.revision=\"${KEELINE_IMAGE_REVISION}\" \\\n");
    output.push_str("      org.opencontainers.image.licenses=\"${KEELINE_IMAGE_LICENSES}\" \\\n");
    writeln!(
        output,
        "      org.opencontainers.image.version=\"{}\"",
        docker_escape(&target.version)
    )?;
    Ok(())
}

fn append_apt_install(
    output: &mut String,
    packages: &[String],
    configure_locales: bool,
) -> Result<()> {
    output.push_str("RUN set -eux; \\\n");
    output.push_str("    apt-get update; \\\n");
    output.push_str(
        "    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\\n",
    );
    for package in packages {
        writeln!(output, "        {package} \\")?;
    }
    output.push_str("    ; \\\n");
    if configure_locales {
        output.push_str("    echo \"en_US.UTF-8 UTF-8\" > /etc/locale.gen; \\\n");
        output.push_str("    locale-gen en_US.UTF-8; \\\n");
    }
    output.push_str("    rm -rf /var/lib/apt/lists/*\n");
    Ok(())
}

fn render_archive_case_statement(archives: &[SourceArchive]) -> Result<String> {
    let mut output = String::new();

    for archive in archives {
        writeln!(
            output,
            "        {}) \\",
            dpkg_arch_for_platform(&archive.platform)?
        )?;
        writeln!(
            output,
            "            ESUM={}; \\",
            shell_quote(&archive.sha256)
        )?;
        writeln!(
            output,
            "            BINARY_URL={}; \\",
            shell_quote(&archive.url)
        )?;
        output.push_str("            ;; \\\n");
    }

    output.push_str("        *) \\\n");
    output.push_str("            echo \"Unsupported arch: ${ARCH}\"; \\\n");
    output.push_str("            exit 1; \\\n");
    output.push_str("            ;; \\\n");

    Ok(output)
}

fn dpkg_arch_for_platform(platform: &str) -> Result<&'static str> {
    match platform {
        "linux/amd64" => Ok("amd64"),
        "linux/arm64" => Ok("arm64"),
        other => bail!("unsupported platform `{other}`"),
    }
}

fn builder_image(base_image: &str) -> String {
    if let Some((repository, tag)) = split_image_reference(base_image) {
        if matches!(
            repository,
            "debian" | "docker.io/debian" | "docker.io/library/debian"
        ) {
            if tag.ends_with("-slim") {
                return base_image.to_string();
            }

            return format!("{repository}:{tag}-slim");
        }
    }

    base_image.to_string()
}

fn split_image_reference(reference: &str) -> Option<(&str, &str)> {
    let last_slash = reference.rfind('/').unwrap_or(0);
    let last_colon = reference.rfind(':')?;

    if last_colon < last_slash {
        return None;
    }

    Some((&reference[..last_colon], &reference[last_colon + 1..]))
}

fn normalize_trim_path(path: &str) -> String {
    if path.starts_with('/') || path.starts_with("$JAVA_HOME/") {
        path.to_string()
    } else {
        format!("$JAVA_HOME/{path}")
    }
}

fn docker_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

#[cfg(test)]
mod tests {
    use super::{builder_image, normalize_trim_path};

    #[test]
    fn derives_slim_builder_image_from_full_debian_base() {
        assert_eq!(
            builder_image("docker.io/library/debian:13"),
            "docker.io/library/debian:13-slim"
        );
        assert_eq!(
            builder_image("docker.io/library/debian:13-slim"),
            "docker.io/library/debian:13-slim"
        );
    }

    #[test]
    fn normalizes_trim_paths_under_java_home() {
        assert_eq!(normalize_trim_path("lib/src.zip"), "$JAVA_HOME/lib/src.zip");
        assert_eq!(normalize_trim_path("/tmp/example"), "/tmp/example");
    }
}
