schema = 1
family = "debian"
line = "13"
version = "13"
distro = "trixie"
id = "debian-13"
package = "keeline-debian"
publish = true
status = "stable"
platforms = ["linux/amd64", "linux/arm64"]

[init]
provider = "tino"
release = "0.1.15"
binary_path = "/sbin/tino"
entrypoint = ["/sbin/tino", "-g", "-s", "--"]

[[init.archives]]
platform = "linux/amd64"
url = "https://github.com/lvillis/tino/releases/download/0.1.15/tino-0.1.15-x86_64-unknown-linux-musl.tar.gz"
sha256 = "4dc414d63bcc589a7c2f49e11004ba7ace0ea2a3c055df3bfd5c6406bb3b4444"

[[init.archives]]
platform = "linux/arm64"
url = "https://github.com/lvillis/tino/releases/download/0.1.15/tino-0.1.15-aarch64-unknown-linux-musl.tar.gz"
sha256 = "a394b7c9356d6a99620e90a1e28aecca35799573a73093ed57405170d25c8584"

[healthcheck]
provider = "salus"
release = "0.1.6"
binary_path = "/bin/salus"
strip_components = 0

[[healthcheck.archives]]
platform = "linux/amd64"
url = "https://github.com/lvillis/salus-rs/releases/download/0.1.6/salus-0.1.6-linux-x86_64-musl.tar.gz"
sha256 = "7bb2d5f5563fb161665f0181230eb4ca95f9c91b963a907be51ecac5b77f6566"

[[healthcheck.archives]]
platform = "linux/arm64"
url = "https://github.com/lvillis/salus-rs/releases/download/0.1.6/salus-0.1.6-linux-aarch64-musl.tar.gz"
sha256 = "c8956206617dbe0d8982f0eb4f8f00e950fec69ab521ff70815b5751d8a7dd77"

[[variants]]
name = "default"
dockerfile = "Dockerfile"
base_image = "docker.io/library/debian:13"
title = "Keeline Debian 13"
description = "Keeline Debian 13 (trixie) base image"
command = ["bash"]
canonical = ["13"]
alias = ["trixie"]

[[variants]]
name = "slim"
dockerfile = "slim.Dockerfile"
base_image = "docker.io/library/debian:13-slim"
title = "Keeline Debian 13 Slim"
description = "Keeline Debian 13 (trixie) slim base image"
command = ["bash"]
canonical = ["13-slim"]
alias = ["trixie-slim"]
